import Foundation

/// Factory helpers that synthesise minimal ArkheEvent values from Hermes WS frames.
/// These keep ApprovalsStore.ingest() working without modification.
extension ArkheEvent {
    static func hermesApproval(_ payload: HermesApprovalPayload) -> ArkheEvent {
        ArkheEvent(
            id: payload.approvalId,
            ts: ISO8601DateFormatter().string(from: Date()),
            schemaVersion: "1",
            missionId: payload.missionId,
            workspaceId: nil,
            agentId: payload.requestedBy,
            parentAgentId: nil,
            eventType: "approval.requested",
            payload: EventPayload(
                title: nil,
                status: "pending",
                objective: nil,
                budgetUsd: nil,
                budgetUsedUsd: nil,
                completionPct: nil,
                riskScore: nil,
                spawnedAgentIds: nil,
                agentId: payload.requestedBy,
                kind: nil,
                role: nil,
                healthScore: nil,
                message: nil,
                fromAgentId: nil,
                toAgentId: nil,
                workItemId: nil,
                handoffReason: nil,
                taskClass: nil,
                provider: nil,
                model: nil,
                reason: nil,
                confidence: nil,
                layer: nil,
                latencyMs: nil,
                outputPreview: nil,
                toolName: nil,
                riskClass: payload.riskClass,
                url: nil,
                transcript: nil,
                intent: nil,
                summary: payload.summary,
                action: payload.action,
                approvalId: payload.approvalId,
                topic: nil,
                opportunityScore: nil,
                velocity: nil,
                searchGrowthPct: nil,
                competitionScore: nil,
                views: nil,
                ctr: nil,
                watchTimeAvgSec: nil,
                retentionPct: nil,
                videoProvider: nil,
                platform: nil,
                assetType: nil,
                error: nil,
                sampleIntervalMs: nil,
                system: nil,
                agents: nil
            )
        )
    }

    static func hermesApprovalResolved(approvalId: String, granted: Bool) -> ArkheEvent {
        ArkheEvent(
            id: UUID().uuidString,
            ts: ISO8601DateFormatter().string(from: Date()),
            schemaVersion: "1",
            missionId: nil,
            workspaceId: nil,
            agentId: nil,
            parentAgentId: nil,
            eventType: granted ? "approval.granted" : "approval.denied",
            payload: EventPayload(
                title: nil,
                status: granted ? "approved" : "denied",
                objective: nil,
                budgetUsd: nil,
                budgetUsedUsd: nil,
                completionPct: nil,
                riskScore: nil,
                spawnedAgentIds: nil,
                agentId: nil,
                kind: nil,
                role: nil,
                healthScore: nil,
                message: nil,
                fromAgentId: nil,
                toAgentId: nil,
                workItemId: nil,
                handoffReason: nil,
                taskClass: nil,
                provider: nil,
                model: nil,
                reason: nil,
                confidence: nil,
                layer: nil,
                latencyMs: nil,
                outputPreview: nil,
                toolName: nil,
                riskClass: nil,
                url: nil,
                transcript: nil,
                intent: nil,
                summary: granted ? "Approved by Hermes" : "Denied by Hermes",
                action: nil,
                approvalId: approvalId,
                topic: nil,
                opportunityScore: nil,
                velocity: nil,
                searchGrowthPct: nil,
                competitionScore: nil,
                views: nil,
                ctr: nil,
                watchTimeAvgSec: nil,
                retentionPct: nil,
                videoProvider: nil,
                platform: nil,
                assetType: nil,
                error: nil,
                sampleIntervalMs: nil,
                system: nil,
                agents: nil
            )
        )
    }
}
