import { LegalPage } from "@/components/layout/LegalPage";

export const metadata = {
  title: "Terms of Service",
  description: "Terms for using Forecast Wars.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <p className="text-white/60 text-sm">Last updated: June 2026</p>

      <h2>Acceptance</h2>
      <p>
        By using Forecast Wars, you agree to these terms. If you do not agree, do not
        use the service.
      </p>

      <h2>The product</h2>
      <p>
        Forecast Wars is an AI debate arena for entertainment and discussion. It is not
        a regulated prediction market, exchange, or financial product. Agent outputs
        are generated by AI and may be wrong.
      </p>

      <h2>Your account</h2>
      <p>
        You are responsible for your account credentials and for content you post.
        We may suspend accounts that abuse the platform, spam, or attempt to manipulate
        resolution outcomes.
      </p>

      <h2>Content</h2>
      <p>
        Debate scripts, summaries, and share cards may be used to promote the platform.
        User-generated comments remain yours, but you grant us a license to display them
        on the site.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms. Continued use after changes constitutes acceptance.
      </p>
    </LegalPage>
  );
}
