#!/usr/bin/env bash
# Sync Forecast Wars local env from repo root .env
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [ ! -f .env ]; then
  echo "Missing $ROOT/.env — copy .env.example and fill Supabase keys."
  exit 1
fi

set -a
# shellcheck disable=SC1091
source .env
set +a

SUPABASE_URL="${SUPABASE_URL:-}"
PUBLISHABLE="${SUPABASE_PUBLISHABLE_KEY:-${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}}"
SECRET="${SUPABASE_SECRET_KEY:-${SUPABASE_SERVICE_ROLE_KEY:-}}"

if [ -z "$SUPABASE_URL" ] || [ -z "$PUBLISHABLE" ] || [ -z "$SECRET" ]; then
  echo "Root .env needs SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, and SUPABASE_SECRET_KEY"
  exit 1
fi

set_env_var() {
  local file="$1" key="$2" value="$3"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    # macOS sed requires backup extension
    sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
  else
    echo "${key}=${value}" >> "$file"
  fi
}

FW_ENV="$ROOT/apps/forecast-wars/.env.local"
cat > "$FW_ENV" <<EOF
# Generated by scripts/sync-forecast-wars-env.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$PUBLISHABLE
SUPABASE_SERVICE_ROLE_KEY=$SECRET
HERMES_URL=http://127.0.0.1:4000
ARKHE_DEBATE_WEBHOOK_URL=http://127.0.0.1:9471
NEXT_PUBLIC_APP_URL=http://localhost:3001
FORECAST_WARS_ADMIN_EMAILS=${FORECAST_WARS_ADMIN_EMAILS:-}
EOF

DAEMON_ENV="$ROOT/apps/local-daemon/.env"
if [ ! -f "$DAEMON_ENV" ]; then
  cp "$ROOT/apps/local-daemon/.env.example" "$DAEMON_ENV"
fi
set_env_var "$DAEMON_ENV" "SUPABASE_URL" "$SUPABASE_URL"
set_env_var "$DAEMON_ENV" "SUPABASE_SERVICE_ROLE_KEY" "$SECRET"
set_env_var "$DAEMON_ENV" "SUPABASE_SECRET_KEY" "$SECRET"
set_env_var "$DAEMON_ENV" "HERMES_URL" "http://127.0.0.1:4000"
set_env_var "$DAEMON_ENV" "ARKHE_FORECAST_WARS_FOCUS" "1"
set_env_var "$DAEMON_ENV" "ARKHE_AUTO_APPROVE" "1"
set_env_var "$DAEMON_ENV" "ARKHE_DEBATE_WEBHOOK_PORT" "9471"

HERMES_ENV="$ROOT/apps/hermes/.env"
if [ ! -f "$HERMES_ENV" ]; then
  cp "$ROOT/apps/hermes/.env.example" "$HERMES_ENV"
fi
set_env_var "$HERMES_ENV" "SUPABASE_URL" "$SUPABASE_URL"
set_env_var "$HERMES_ENV" "SUPABASE_SERVICE_ROLE_KEY" "$SECRET"

echo "✓ Wrote $FW_ENV"
echo "✓ Updated $DAEMON_ENV"
echo "✓ Updated $HERMES_ENV"
echo ""
echo "Next: pnpm start:forecast-wars"
